permalink: /:year/:month/:day/:title.html
markdown: kramdown
encoding: utf-8
#pygments: true
highlighter: pygments
kramdown:
  input: GFM

# 作者信息
author: 
  name: zp
  email: zp6282154@163.com
  link:  http://github.com/justzhao

  github: http://github.com/justzhao

# 站点信息
title: 赵鹏励志成为架构师的Javaer
description: 赵鹏
url:  http://github.com/justzhao
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7x00ae.com1.z0.glb.clouddn.com/javaGC.jpg
favicon: http://7x00ae.com1.z0.glb.clouddn.com/javaGC.jpg

# google analytics 设置
#ga:
 # id: UA-54767140-1
 # url: yansu.org

# disqus 设置
#disqus:
 # shortname: suyan-zh